//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectServer.ServiceApp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/WCFApp.DTO")]
    [System.SerializableAttribute()]
    public partial class Teacher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CMNDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CMND {
            get {
                return this.CMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.CMNDField, value) != true)) {
                    this.CMNDField = value;
                    this.RaisePropertyChanged("CMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher_Student_Mapping", Namespace="http://schemas.datacontract.org/2004/07/WCFApp.DTO")]
    [System.SerializableAttribute()]
    public partial class Teacher_Student_Mapping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectServer.ServiceApp.Parent parentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectServer.ServiceApp.Student studentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectServer.ServiceApp.Parent parent {
            get {
                return this.parentField;
            }
            set {
                if ((object.ReferenceEquals(this.parentField, value) != true)) {
                    this.parentField = value;
                    this.RaisePropertyChanged("parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectServer.ServiceApp.Student student {
            get {
                return this.studentField;
            }
            set {
                if ((object.ReferenceEquals(this.studentField, value) != true)) {
                    this.studentField = value;
                    this.RaisePropertyChanged("student");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parent", Namespace="http://schemas.datacontract.org/2004/07/WCFApp.DTO")]
    [System.SerializableAttribute()]
    public partial class Parent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CMNDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CMND {
            get {
                return this.CMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.CMNDField, value) != true)) {
                    this.CMNDField = value;
                    this.RaisePropertyChanged("CMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WCFApp.DTO")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="History", Namespace="http://schemas.datacontract.org/2004/07/WCFApp.DTO")]
    [System.SerializableAttribute()]
    public partial class History : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectServer.ServiceApp.MessageContent messageContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectServer.ServiceApp.Parent parentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((this.StatusMessageField.Equals(value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectServer.ServiceApp.MessageContent messageContent {
            get {
                return this.messageContentField;
            }
            set {
                if ((object.ReferenceEquals(this.messageContentField, value) != true)) {
                    this.messageContentField = value;
                    this.RaisePropertyChanged("messageContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectServer.ServiceApp.Parent parent {
            get {
                return this.parentField;
            }
            set {
                if ((object.ReferenceEquals(this.parentField, value) != true)) {
                    this.parentField = value;
                    this.RaisePropertyChanged("parent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageContent", Namespace="http://schemas.datacontract.org/2004/07/WCFApp.DTO")]
    [System.SerializableAttribute()]
    public partial class MessageContent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeNeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeSendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeMessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectServer.ServiceApp.TypeMessage typeMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusPriority {
            get {
                return this.StatusPriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusPriorityField, value) != true)) {
                    this.StatusPriorityField = value;
                    this.RaisePropertyChanged("StatusPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeNeed {
            get {
                return this.TimeNeedField;
            }
            set {
                if ((this.TimeNeedField.Equals(value) != true)) {
                    this.TimeNeedField = value;
                    this.RaisePropertyChanged("TimeNeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeSend {
            get {
                return this.TimeSendField;
            }
            set {
                if ((this.TimeSendField.Equals(value) != true)) {
                    this.TimeSendField = value;
                    this.RaisePropertyChanged("TimeSend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeMessageId {
            get {
                return this.TypeMessageIdField;
            }
            set {
                if ((this.TypeMessageIdField.Equals(value) != true)) {
                    this.TypeMessageIdField = value;
                    this.RaisePropertyChanged("TypeMessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectServer.ServiceApp.TypeMessage typeM {
            get {
                return this.typeMField;
            }
            set {
                if ((object.ReferenceEquals(this.typeMField, value) != true)) {
                    this.typeMField = value;
                    this.RaisePropertyChanged("typeM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeMessage", Namespace="http://schemas.datacontract.org/2004/07/WCFApp.DTO")]
    [System.SerializableAttribute()]
    public partial class TypeMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionTypeMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionTypeMessage {
            get {
                return this.DescriptionTypeMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionTypeMessageField, value) != true)) {
                    this.DescriptionTypeMessageField = value;
                    this.RaisePropertyChanged("DescriptionTypeMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class", Namespace="http://schemas.datacontract.org/2004/07/WCFApp.DTO")]
    [System.SerializableAttribute()]
    public partial class Class : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusClassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusClass {
            get {
                return this.StatusClassField;
            }
            set {
                if ((this.StatusClassField.Equals(value) != true)) {
                    this.StatusClassField = value;
                    this.RaisePropertyChanged("StatusClass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceApp.IServiceApp")]
    public interface IServiceApp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/checkLoginTeacher", ReplyAction="http://tempuri.org/IServiceApp/checkLoginTeacherResponse")]
        ProjectServer.ServiceApp.Teacher checkLoginTeacher(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/checkLoginTeacher", ReplyAction="http://tempuri.org/IServiceApp/checkLoginTeacherResponse")]
        System.Threading.Tasks.Task<ProjectServer.ServiceApp.Teacher> checkLoginTeacherAsync(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/sendMessage", ReplyAction="http://tempuri.org/IServiceApp/sendMessageResponse")]
        string[] sendMessage(string TeacherId, string Message, string[] listNumberPhone, string[] listParents, string StatusPriority, int TypeMessageId, System.DateTime TimeSend, System.DateTime TimeNeed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/sendMessage", ReplyAction="http://tempuri.org/IServiceApp/sendMessageResponse")]
        System.Threading.Tasks.Task<string[]> sendMessageAsync(string TeacherId, string Message, string[] listNumberPhone, string[] listParents, string StatusPriority, int TypeMessageId, System.DateTime TimeSend, System.DateTime TimeNeed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/getStudent_Parent_ByTeacherId", ReplyAction="http://tempuri.org/IServiceApp/getStudent_Parent_ByTeacherIdResponse")]
        ProjectServer.ServiceApp.Teacher_Student_Mapping[] getStudent_Parent_ByTeacherId(int TeacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/getStudent_Parent_ByTeacherId", ReplyAction="http://tempuri.org/IServiceApp/getStudent_Parent_ByTeacherIdResponse")]
        System.Threading.Tasks.Task<ProjectServer.ServiceApp.Teacher_Student_Mapping[]> getStudent_Parent_ByTeacherIdAsync(int TeacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/getHistoryByTeacherId", ReplyAction="http://tempuri.org/IServiceApp/getHistoryByTeacherIdResponse")]
        ProjectServer.ServiceApp.History[] getHistoryByTeacherId(int TeacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/getHistoryByTeacherId", ReplyAction="http://tempuri.org/IServiceApp/getHistoryByTeacherIdResponse")]
        System.Threading.Tasks.Task<ProjectServer.ServiceApp.History[]> getHistoryByTeacherIdAsync(int TeacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/getAllTeacher", ReplyAction="http://tempuri.org/IServiceApp/getAllTeacherResponse")]
        ProjectServer.ServiceApp.Teacher[] getAllTeacher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/getAllTeacher", ReplyAction="http://tempuri.org/IServiceApp/getAllTeacherResponse")]
        System.Threading.Tasks.Task<ProjectServer.ServiceApp.Teacher[]> getAllTeacherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/getAllClass", ReplyAction="http://tempuri.org/IServiceApp/getAllClassResponse")]
        ProjectServer.ServiceApp.Class[] getAllClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/getAllClass", ReplyAction="http://tempuri.org/IServiceApp/getAllClassResponse")]
        System.Threading.Tasks.Task<ProjectServer.ServiceApp.Class[]> getAllClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/updateClassAndTeacher", ReplyAction="http://tempuri.org/IServiceApp/updateClassAndTeacherResponse")]
        bool updateClassAndTeacher(int classId, int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/updateClassAndTeacher", ReplyAction="http://tempuri.org/IServiceApp/updateClassAndTeacherResponse")]
        System.Threading.Tasks.Task<bool> updateClassAndTeacherAsync(int classId, int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test1", ReplyAction="http://tempuri.org/IServiceApp/test1Response")]
        void test1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test1", ReplyAction="http://tempuri.org/IServiceApp/test1Response")]
        System.Threading.Tasks.Task test1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test2", ReplyAction="http://tempuri.org/IServiceApp/test2Response")]
        void test2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test2", ReplyAction="http://tempuri.org/IServiceApp/test2Response")]
        System.Threading.Tasks.Task test2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test3", ReplyAction="http://tempuri.org/IServiceApp/test3Response")]
        void test3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test3", ReplyAction="http://tempuri.org/IServiceApp/test3Response")]
        System.Threading.Tasks.Task test3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test4", ReplyAction="http://tempuri.org/IServiceApp/test4Response")]
        void test4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test4", ReplyAction="http://tempuri.org/IServiceApp/test4Response")]
        System.Threading.Tasks.Task test4Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test5", ReplyAction="http://tempuri.org/IServiceApp/test5Response")]
        void test5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test5", ReplyAction="http://tempuri.org/IServiceApp/test5Response")]
        System.Threading.Tasks.Task test5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test6", ReplyAction="http://tempuri.org/IServiceApp/test6Response")]
        void test6();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test6", ReplyAction="http://tempuri.org/IServiceApp/test6Response")]
        System.Threading.Tasks.Task test6Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test7", ReplyAction="http://tempuri.org/IServiceApp/test7Response")]
        void test7();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApp/test7", ReplyAction="http://tempuri.org/IServiceApp/test7Response")]
        System.Threading.Tasks.Task test7Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAppChannel : ProjectServer.ServiceApp.IServiceApp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAppClient : System.ServiceModel.ClientBase<ProjectServer.ServiceApp.IServiceApp>, ProjectServer.ServiceApp.IServiceApp {
        
        public ServiceAppClient() {
        }
        
        public ServiceAppClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAppClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAppClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAppClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProjectServer.ServiceApp.Teacher checkLoginTeacher(string Username, string Password) {
            return base.Channel.checkLoginTeacher(Username, Password);
        }
        
        public System.Threading.Tasks.Task<ProjectServer.ServiceApp.Teacher> checkLoginTeacherAsync(string Username, string Password) {
            return base.Channel.checkLoginTeacherAsync(Username, Password);
        }
        
        public string[] sendMessage(string TeacherId, string Message, string[] listNumberPhone, string[] listParents, string StatusPriority, int TypeMessageId, System.DateTime TimeSend, System.DateTime TimeNeed) {
            return base.Channel.sendMessage(TeacherId, Message, listNumberPhone, listParents, StatusPriority, TypeMessageId, TimeSend, TimeNeed);
        }
        
        public System.Threading.Tasks.Task<string[]> sendMessageAsync(string TeacherId, string Message, string[] listNumberPhone, string[] listParents, string StatusPriority, int TypeMessageId, System.DateTime TimeSend, System.DateTime TimeNeed) {
            return base.Channel.sendMessageAsync(TeacherId, Message, listNumberPhone, listParents, StatusPriority, TypeMessageId, TimeSend, TimeNeed);
        }
        
        public ProjectServer.ServiceApp.Teacher_Student_Mapping[] getStudent_Parent_ByTeacherId(int TeacherId) {
            return base.Channel.getStudent_Parent_ByTeacherId(TeacherId);
        }
        
        public System.Threading.Tasks.Task<ProjectServer.ServiceApp.Teacher_Student_Mapping[]> getStudent_Parent_ByTeacherIdAsync(int TeacherId) {
            return base.Channel.getStudent_Parent_ByTeacherIdAsync(TeacherId);
        }
        
        public ProjectServer.ServiceApp.History[] getHistoryByTeacherId(int TeacherId) {
            return base.Channel.getHistoryByTeacherId(TeacherId);
        }
        
        public System.Threading.Tasks.Task<ProjectServer.ServiceApp.History[]> getHistoryByTeacherIdAsync(int TeacherId) {
            return base.Channel.getHistoryByTeacherIdAsync(TeacherId);
        }
        
        public ProjectServer.ServiceApp.Teacher[] getAllTeacher() {
            return base.Channel.getAllTeacher();
        }
        
        public System.Threading.Tasks.Task<ProjectServer.ServiceApp.Teacher[]> getAllTeacherAsync() {
            return base.Channel.getAllTeacherAsync();
        }
        
        public ProjectServer.ServiceApp.Class[] getAllClass() {
            return base.Channel.getAllClass();
        }
        
        public System.Threading.Tasks.Task<ProjectServer.ServiceApp.Class[]> getAllClassAsync() {
            return base.Channel.getAllClassAsync();
        }
        
        public bool updateClassAndTeacher(int classId, int teacherId) {
            return base.Channel.updateClassAndTeacher(classId, teacherId);
        }
        
        public System.Threading.Tasks.Task<bool> updateClassAndTeacherAsync(int classId, int teacherId) {
            return base.Channel.updateClassAndTeacherAsync(classId, teacherId);
        }
        
        public void test1() {
            base.Channel.test1();
        }
        
        public System.Threading.Tasks.Task test1Async() {
            return base.Channel.test1Async();
        }
        
        public void test2() {
            base.Channel.test2();
        }
        
        public System.Threading.Tasks.Task test2Async() {
            return base.Channel.test2Async();
        }
        
        public void test3() {
            base.Channel.test3();
        }
        
        public System.Threading.Tasks.Task test3Async() {
            return base.Channel.test3Async();
        }
        
        public void test4() {
            base.Channel.test4();
        }
        
        public System.Threading.Tasks.Task test4Async() {
            return base.Channel.test4Async();
        }
        
        public void test5() {
            base.Channel.test5();
        }
        
        public System.Threading.Tasks.Task test5Async() {
            return base.Channel.test5Async();
        }
        
        public void test6() {
            base.Channel.test6();
        }
        
        public System.Threading.Tasks.Task test6Async() {
            return base.Channel.test6Async();
        }
        
        public void test7() {
            base.Channel.test7();
        }
        
        public System.Threading.Tasks.Task test7Async() {
            return base.Channel.test7Async();
        }
    }
}
