package com.herosky.hackathon.hackathonedumobileclient.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.1
//
// Created by Quasar Development at 01-08-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PBGTeacher extends AttributeContainer implements KvmSerializable
{
    
    public String Address;
    
    public String CMND;
    
    public String Email;
    
    public String FullName;
    
    public String ImagePath;
    
    public String Password;
    
    public String PhoneNumber;
    
    public String Status;
    
    public Integer TeacherId;
    
    public Integer TypeId;
    
    public String Username;

    public PBGTeacher ()
    {
    }

    public PBGTeacher (java.lang.Object paramObj,PBGExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Address"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Address");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Address = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Address = (String)obj;
            }    
        }
        if (soapObject.hasProperty("CMND"))
        {	
	        java.lang.Object obj = soapObject.getProperty("CMND");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.CMND = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.CMND = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Email"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Email = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Email = (String)obj;
            }    
        }
        if (soapObject.hasProperty("FullName"))
        {	
	        java.lang.Object obj = soapObject.getProperty("FullName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.FullName = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.FullName = (String)obj;
            }    
        }
        if (soapObject.hasProperty("ImagePath"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ImagePath");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ImagePath = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.ImagePath = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Password"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Password");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Password = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Password = (String)obj;
            }    
        }
        if (soapObject.hasProperty("PhoneNumber"))
        {	
	        java.lang.Object obj = soapObject.getProperty("PhoneNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.PhoneNumber = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.PhoneNumber = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Status"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Status");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Status = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Status = (String)obj;
            }    
        }
        if (soapObject.hasProperty("TeacherId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("TeacherId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.TeacherId = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.TeacherId = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("TypeId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("TypeId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.TypeId = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.TypeId = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("Username"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Username");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Username = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Username = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Address!=null?this.Address:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.CMND!=null?this.CMND:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Email!=null?this.Email:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.FullName!=null?this.FullName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.ImagePath!=null?this.ImagePath:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Password!=null?this.Password:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.PhoneNumber!=null?this.PhoneNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Status!=null?this.Status:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.TeacherId!=null?this.TeacherId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.TypeId!=null?this.TypeId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.Username!=null?this.Username:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 11;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Address";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CMND";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Email";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FullName";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ImagePath";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Password";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PhoneNumber";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Status";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TeacherId";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TypeId";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Username";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
