package com.herosky.hackathon.hackathonedumobileclient.ws2;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.1
//
// Created by Quasar Development at 02-08-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QMPHistory extends AttributeContainer implements KvmSerializable
{
    public boolean isCheck = false;
    public Integer Id;
    
    public Integer MessageId;
    
    public Integer ParentId;
    
    public Integer StatusMessage;
    
    public Integer TeacherId;
    
    public QMPMessageContent messageContent;
    
    public QMPParent parent;

    public QMPHistory ()
    {
    }

    public QMPHistory (java.lang.Object paramObj,QMPExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Id"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Id = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.Id = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("MessageId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("MessageId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.MessageId = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.MessageId = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("ParentId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ParentId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ParentId = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.ParentId = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("StatusMessage"))
        {	
	        java.lang.Object obj = soapObject.getProperty("StatusMessage");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.StatusMessage = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.StatusMessage = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("TeacherId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("TeacherId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.TeacherId = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.TeacherId = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("messageContent"))
        {	
	        java.lang.Object j = soapObject.getProperty("messageContent");
	        this.messageContent = (QMPMessageContent)__envelope.get(j,QMPMessageContent.class);
        }
        if (soapObject.hasProperty("parent"))
        {	
	        java.lang.Object j = soapObject.getProperty("parent");
	        this.parent = (QMPParent)__envelope.get(j,QMPParent.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.MessageId!=null?this.MessageId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ParentId!=null?this.ParentId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.StatusMessage!=null?this.StatusMessage:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.TeacherId!=null?this.TeacherId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.messageContent!=null?this.messageContent:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.parent!=null?this.parent:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "MessageId";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ParentId";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusMessage";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TeacherId";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==5)
        {
            info.type = QMPMessageContent.class;
            info.name = "messageContent";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==6)
        {
            info.type = QMPParent.class;
            info.name = "parent";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
