package com.herosky.hackathon.hackathonedumobileclient.ws2;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.1
//
// Created by Quasar Development at 02-08-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QMPMessageContent extends AttributeContainer implements KvmSerializable
{
    
    public String Content;
    
    public Integer Id;
    
    public String StatusPriority;
    
    public java.util.Date TimeNeed;
    
    public java.util.Date TimeSend;
    
    public Integer TypeMessageId;
    
    public QMPTypeMessage typeM;

    public QMPMessageContent ()
    {
    }

    public QMPMessageContent (java.lang.Object paramObj,QMPExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Content"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Content");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Content = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Content = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Id"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Id = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.Id = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("StatusPriority"))
        {	
	        java.lang.Object obj = soapObject.getProperty("StatusPriority");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.StatusPriority = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.StatusPriority = (String)obj;
            }    
        }
        if (soapObject.hasProperty("TimeNeed"))
        {	
	        java.lang.Object obj = soapObject.getProperty("TimeNeed");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.TimeNeed = QMPHelper.ConvertFromWebService(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof java.util.Date){
                this.TimeNeed = (java.util.Date)obj;
            }    
        }
        if (soapObject.hasProperty("TimeSend"))
        {	
	        java.lang.Object obj = soapObject.getProperty("TimeSend");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.TimeSend = QMPHelper.ConvertFromWebService(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof java.util.Date){
                this.TimeSend = (java.util.Date)obj;
            }    
        }
        if (soapObject.hasProperty("TypeMessageId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("TypeMessageId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.TypeMessageId = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.TypeMessageId = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("typeM"))
        {	
	        java.lang.Object j = soapObject.getProperty("typeM");
	        this.typeM = (QMPTypeMessage)__envelope.get(j,QMPTypeMessage.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Content!=null?this.Content:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.StatusPriority!=null?this.StatusPriority:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.TimeNeed!=null?QMPHelper.getDateTimeFormat().format(this.TimeNeed):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.TimeSend!=null?QMPHelper.getDateTimeFormat().format(this.TimeSend):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.TypeMessageId!=null?this.TypeMessageId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.typeM!=null?this.typeM:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Content";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "StatusPriority";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TimeNeed";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TimeSend";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TypeMessageId";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==6)
        {
            info.type = QMPTypeMessage.class;
            info.name = "typeM";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
