package com.herosky.hackathon.hackathonedumobileclient.ws2;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.1
//
// Created by Quasar Development at 02-08-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QMPParent extends AttributeContainer implements KvmSerializable
{
    
    public String Address;
    
    public String CMND;
    
    public String Email;
    
    public String FullName;
    
    public Integer ParentId;
    
    public String PhoneNumber;
    
    public String Status;
    
    public Integer StudentId;

    public QMPParent ()
    {
    }

    public QMPParent (java.lang.Object paramObj,QMPExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Address"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Address");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Address = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Address = (String)obj;
            }    
        }
        if (soapObject.hasProperty("CMND"))
        {	
	        java.lang.Object obj = soapObject.getProperty("CMND");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.CMND = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.CMND = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Email"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Email = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Email = (String)obj;
            }    
        }
        if (soapObject.hasProperty("FullName"))
        {	
	        java.lang.Object obj = soapObject.getProperty("FullName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.FullName = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.FullName = (String)obj;
            }    
        }
        if (soapObject.hasProperty("ParentId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ParentId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ParentId = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.ParentId = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("PhoneNumber"))
        {	
	        java.lang.Object obj = soapObject.getProperty("PhoneNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.PhoneNumber = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.PhoneNumber = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Status"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Status");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Status = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Status = (String)obj;
            }    
        }
        if (soapObject.hasProperty("StudentId"))
        {	
	        java.lang.Object obj = soapObject.getProperty("StudentId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.StudentId = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.StudentId = (Integer)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Address!=null?this.Address:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.CMND!=null?this.CMND:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Email!=null?this.Email:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.FullName!=null?this.FullName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.ParentId!=null?this.ParentId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.PhoneNumber!=null?this.PhoneNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.Status!=null?this.Status:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.StudentId!=null?this.StudentId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Address";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CMND";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Email";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FullName";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ParentId";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PhoneNumber";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Status";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StudentId";
            info.namespace= "http://schemas.datacontract.org/2004/07/WCFApp.DTO";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
