package com.herosky.hackathon.hackathonedumobileclient.ws2;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.1
//
// Created by Quasar Development at 02-08-2015
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class ServiceClient2
{
    interface QMPIWcfMethod
    {
        QMPExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(QMPExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://10.0.240.221:56481/ServiceApp.svc";

    int timeOut=20000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    public ServiceClient2(){}

    public ServiceClient2(String url)
    {
        this.url = url;
    }

    public ServiceClient2(String url, int timeOut)
    {
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected QMPExtendedSoapSerializationEnvelope createEnvelope()
    {
        QMPExtendedSoapSerializationEnvelope envelope= new QMPExtendedSoapSerializationEnvelope(QMPExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,QMPExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,QMPExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public QMPTeacher checkLoginTeacher(final String Username,final String Password ) throws java.lang.Exception
    {
        return (QMPTeacher)execute(new QMPIWcfMethod()
        {
            @Override
            public QMPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              QMPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "checkLoginTeacher");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="Username";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Username!=null?Username:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="Password";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Password!=null?Password:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(QMPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (QMPTeacher)getResult(QMPTeacher.class,__result,"checkLoginTeacherResult",__envelope);
            }
        },"http://tempuri.org/IServiceApp/checkLoginTeacher");
    }
    
    public QMPArrayOfstring sendMessage(final String TeacherId,final String Message,final QMPArrayOfstring listNumberPhone,final QMPArrayOfstring listParents,final String StatusPriority,final Integer TypeMessageId,final java.util.Date TimeSend,final java.util.Date TimeNeed ) throws java.lang.Exception
    {
        return (QMPArrayOfstring)execute(new QMPIWcfMethod()
        {
            @Override
            public QMPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              QMPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","listNumberPhone",new QMPArrayOfstring().getClass());
                __envelope.addMapping("http://tempuri.org/","listParents",new QMPArrayOfstring().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "sendMessage");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TeacherId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(TeacherId!=null?TeacherId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="Message";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Message!=null?Message:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="listNumberPhone";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(listNumberPhone!=null?listNumberPhone:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="listParents";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(listParents!=null?listParents:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="StatusPriority";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(StatusPriority!=null?StatusPriority:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TypeMessageId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(TypeMessageId!=null?TypeMessageId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TimeSend";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(TimeSend!=null?QMPHelper.getDateTimeFormat().format(TimeSend):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TimeNeed";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(TimeNeed!=null?QMPHelper.getDateTimeFormat().format(TimeNeed):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(QMPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (QMPArrayOfstring)getResult(QMPArrayOfstring.class,__result,"sendMessageResult",__envelope);
            }
        },"http://tempuri.org/IServiceApp/sendMessage");
    }
    
    public QMPArrayOfTeacher_Student_Mapping getStudent_Parent_ByTeacherId(final Integer TeacherId ) throws java.lang.Exception
    {
        return (QMPArrayOfTeacher_Student_Mapping)execute(new QMPIWcfMethod()
        {
            @Override
            public QMPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              QMPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "getStudent_Parent_ByTeacherId");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TeacherId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(TeacherId!=null?TeacherId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(QMPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (QMPArrayOfTeacher_Student_Mapping)getResult(QMPArrayOfTeacher_Student_Mapping.class,__result,"getStudent_Parent_ByTeacherIdResult",__envelope);
            }
        },"http://tempuri.org/IServiceApp/getStudent_Parent_ByTeacherId");
    }
    
    public QMPArrayOfHistory getHistoryByTeacherId(final Integer TeacherId ) throws java.lang.Exception
    {
        return (QMPArrayOfHistory)execute(new QMPIWcfMethod()
        {
            @Override
            public QMPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              QMPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "getHistoryByTeacherId");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TeacherId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(TeacherId!=null?TeacherId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(QMPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (QMPArrayOfHistory)getResult(QMPArrayOfHistory.class,__result,"getHistoryByTeacherIdResult",__envelope);
            }
        },"http://tempuri.org/IServiceApp/getHistoryByTeacherId");
    }
    
    public QMPArrayOfTeacher getAllTeacher( ) throws java.lang.Exception
    {
        return (QMPArrayOfTeacher)execute(new QMPIWcfMethod()
        {
            @Override
            public QMPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              QMPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "getAllTeacher");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(QMPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (QMPArrayOfTeacher)getResult(QMPArrayOfTeacher.class,__result,"getAllTeacherResult",__envelope);
            }
        },"http://tempuri.org/IServiceApp/getAllTeacher");
    }
    
    public QMPArrayOfClass getAllClass( ) throws java.lang.Exception
    {
        return (QMPArrayOfClass)execute(new QMPIWcfMethod()
        {
            @Override
            public QMPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              QMPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "getAllClass");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(QMPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (QMPArrayOfClass)getResult(QMPArrayOfClass.class,__result,"getAllClassResult",__envelope);
            }
        },"http://tempuri.org/IServiceApp/getAllClass");
    }
    
    public Boolean updateClassAndTeacher(final Integer classId,final Integer teacherId ) throws java.lang.Exception
    {
        return (Boolean)execute(new QMPIWcfMethod()
        {
            @Override
            public QMPExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              QMPExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "updateClassAndTeacher");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="classId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(classId!=null?classId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="teacherId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(teacherId!=null?teacherId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(QMPExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("updateClassAndTeacherResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServiceApp/updateClassAndTeacher");
    }
    
    public void test1( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void test2( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void test3( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void test4( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void test5( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void test6( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void test7( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }

    
    protected java.lang.Object execute(QMPIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        QMPExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,QMPExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


